### ISSUE TITLE
Center offset when resizing page

### ISSUE THREAD

**Issue by Asjpik** [Niush/floorplanjs#1]
![image](https://user-images.githubusercontent.com/18084046/84885932-612dce00-b09c-11ea-81ec-97aebabb3249.png)

**Comment by Niush** [comment]
Issue is unclear.
Page Resize will always be calculated from the center of the editor screen. Pointer location is not used.

**Comment by Asjpik** [comment]
when placing the wall, the position on the grid does not coincide with the cursor position on the screen

**Comment by Asjpik** [comment]
[Video](https://drive.google.com/file/d/13aAJmMRIActz5HjjO-6SOTJPuoSJReqx/view?usp=sharing)
